server: 8080

#acturator 健康管理-优雅停机配置
management:
  endpoints:
    web:
      exposure:
        include: shutdown,env,mappings,info,metrics,beans,configprops,httptrace,loggers,mappings,sessions,health # web开放endpoint的下面的功能 （ beans，configprops，env，health，info，metrics，mappings，shutdown）
  # endpoint 下面的功能有 beans，configprops，env，health，info，metrics，mappings，shutdown ，详看README.md
  endpoint:
    shutdown:
      enabled: true
    env:
      enabled: true
    health:
      show-details: always


  server:
    port: 8080


